version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    volumes:
      - ./data:/var/lib/cassandra
    ports:
      - 9042:9042
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M